# Site settings
title: My Site
tagline: Writer, editor, ex-bartender, and aspiring world-class breakdancer
footer_tagline: That last one is a bit of a stretch.
email: ryan@ryanwatters.me
description: My name is Ryan. This is my website.
copyright_in_footer: true
baseurl: "" # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
site_owner: Ryan Watters
author_photo: #me.jpg 

# SOCIAL MEDIA/SHARING

#Just add handle without the "@"
twitter: ryandwatters
#Just your username for GitHub, Tumblr, and Pinterest
github:  rdwatters
tumblr: ryandwatters
pinterest: ryandwatters
instagram: ryandwatters 
#Everything after https://www.youtube.com/user/
youtube: Megatull80
#Everything after "facebook.com/" in the URL, regardless of whether it's a personal profile or business page.
facebook: pages/MySitecom/810571539011577
#Everything after "plus.google.com/"  
google_plus: +RyanWattersRyanWatters
#Everything after "https://www.linkedin.com/pub/"
linkedin_profile: ryan-watters-els/25/107/80
#Set RSS to "true" or "false" if you want to include an RSS feed and an RSS icon
include_rss: true

# COMMENTS(DISQUS)
# If you want to remove all comments on all pages at once, removed the shortname from this file
disqus_shortname: ryanwattersme 

# GLOBAL NAVIGATION

main_navigation_links:
- text: Home
  url: 
- text: Articles
  url: articles
- text: About
  url: about
- text: Contact
  url: contact


# COLLECTIONS

permalink: /:title/
collections:
  articles:
    output: true 

# BUILD SETTINGS

markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  syntax_highlighter: rouge


sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all 

# PROSE.IO SETTINGS CAN BE FOUND IN THE _prose.yml FILE


