# Site settings
title: Ryan Watters
tagline: Writer, editor, ex-bartender, and aspiring world-class breakdancer
footer_tagline: That last one is a bit of a stretch.
email: ryan@ryanwatters.me
description: My name is Ryan. This is my website.
copyright_in_footer: true
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://ryansportfol.io # the base hostname & protocol for your site
site_owner: Ryan Watters
site_owner_initials: RW
author_photo: #me.jpg 

# SOCIAL MEDIA/SHARING

#Just add handle without the "@"
twitter: ryandwatters
#Just your username for GitHub, Tumblr, and Pinterest
github:  rdwatters
tumblr: 
pinterest: 
instagram:  
#Everything after https://www.youtube.com/user/
youtube: #Megatull80
#Everything after "facebook.com/" in the URL, regardless of whether it's a personal profile or business page.
facebook: #pages/MySitecom/810571539011577
#Everything after "plus.google.com/"  
googleplus: +RyanWattersRyanWatters
#Everything after "https://www.linkedin.com/pub/"
linkedin: ryan-watters-els/25/107/80
#Set RSS to "true" or "false" if you want to include an RSS feed and an RSS icon
include_rss: true

# GOOGLE ANALYTICS - Usually begins with "UA" followed by 11 digits
googleanalytics: UA-67203548-1

# COMMENTS(DISQUS)
# If you want to remove all comments on all pages at once, removed the shortname from this file
disqus_shortname: ryansportfolio

# GLOBAL NAVIGATION

main_navigation_links: 
- text: Articles
  url: articles
- text: Tutorials
  url: tutorials
- text: About
  url: about
- text: Contact
  url: contact

# COLLECTIONS

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/
permalink: /:collection/:path/

# BUILD SETTINGS

markdown: redcarpet
redcarpet:
  extensions: ['smart','superscript','strikethrough','autolinks','tables','no_intra_emphasis','footnotes', 'tables', 'with_toc_data']
# highlighter: pygments

exclude: [Gemfile,Gemfile.lock,snippets_and_notes.md,grunt]
include: [scripts]

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all 

repository: rdwatters/
gems: ['rouge','redcarpet']

# PROSE.IO SETTINGS

prose:
  siteurl: https://ryansportfol.io
  media: "/assets/images/"
  metadata:
    _articles:
      - name: "updated_date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter the title of this article"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Article Description"
          help: "Write a short description of this article. Try to keep it to less than 200 characters."
      - name: "published_on"
        field:
          label: "When this article was published"
          element: "text"
          placeholder: "Enter as yyyy-mm-dd"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish now"
          help: "Keep this unchecked if you do not want to   publish the article right now"
          value: "true"
      - name: "layout"
        field: 
          element: "hidden"
          value: "article"
      - name: "main_image"
        field:
          element: "text"
          label: "Article image"
          value: "Full filename of the image you want to use"
      - name: "main_image_description"
        field:
          element: "text"
          label: "Article image description"
        value: "Write a descrption of the image used for the   article"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Include comments?"
          value: "true"
      - name: "insearch"
        field:
          element: "checkbox"
          label: "Include in search?"
          value: "true"


