# Only one archetype (posts) is included in Hugo Starter
archetypedir = "archetypes"
baseurl = "https://ryanwatters.io"
buildDrafts = false
buildFuture = false
canonifyurls = true
config = "config.toml"
copyright = "ryanwatters.io"
contentdir = "content"
disableLiveReload= false
disableRSS = false
disableSitemap = false
footnotereturnlinkcontents = "↩"
ignoreFiles = []
languageCode = "en-us"
layoutDir = "layouts"
log = false
metaDataFormat = "yaml"
pluralizelisttitles = false
preserveTaxonomyNames = false
publishdir = "public"
pygmentsUseClasses = true
relativeURLs = true
source = ""
title = "ryanwatters.io"
uglyURLs = false
verbose = true
verboseLog = true
watch = true

[permalinks]
  singletons = "/:title/"

[params]
	SiteAuthor = "Ryan D Watters"
	GitHub = "rdwatters"
  Twitter = "ryandwatters"
  FBAppID = 1389111194449073
  Facebook = ""
  YouTube = ""
  GooglePlus = ""
  DefaultSocialImage = "ryanwattersio-social.jpg"
  LinkedIn = "https://www.linkedin.com/in/ryan-watters-els-08010725"
  GoogleAnalyticsTrackingId = "UA-76549364-1"
  CopyrightLine = "ryanwatters.io"
  CopyrightHolder = "Ryan D. Watters, ELS"
  SiteDescription = "The official website of Ryan Watters - content strategist, content marketer, editor, writer, web publisher, nerd, Japanophile, inchoate front-end developer, and ramen aficionado."
  # If true, site style will be embedded in a <style>
  UseCRP = true
  # Include locally hosted jQuery 2.2.2
  IncludeJQ = false
  UseDisqus = true
  # Include Swiftype Metadata in Head
  Swiftype = true
  disqusShortname = ""
  SitePublishDate = "2016-01-01"

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[taxonomies]
  tag = "tags"
  category = "categories"





