# Only one archetype (posts) is included in Hugo Starter
archetypedir = "archetypes"
baseurl = ""
buildDrafts = false
buildFuture = false
canonifyurls = true
config = "config.toml"
contentdir = "content"
disableLiveReload= false
disableRSS = false
disableSitemap = false
ignoreFiles = []
languageCode = "en-us"
layoutDir = "layouts"
log = false
metaDataFormat = "yaml"
pluralizelisttitles = false
publishdir = "public"
pygmentsUseClasses = true
relativeURLs = true
source = ""
title = "Ryan Watters"
uglyURLs = false
verbose = true
verboseLog = false
watch = true

[permalinks]
  # The temp folder is created for one-off pages (eg, marketing and design-heavy pages that run outside other site templates). Keep in mind that all .md pages under temp still require title and date in the YAML/front matter

[params]
	SiteAuthor = ""
  TwitterHandle = ""
	GitHub = ""
  Twitter = ""
  Facebook = ""
  YouTube = ""
  GooglePlus = ""
  LinkedIn = ""
  GoogleAnalyticsTrackingId = ""
  CopyrightLine = "Ryan D Watters, ELS"
  SiteDescription = "This is a Hugo starter kit developed by Ryan Watters, https://www.github.com/rdwatters"
  # If true, site style will be embedded in a <style> tag in each html <head> by pulling in "style-embed-for-crp-only.html" partial created by default as part of the Gulp Build. If set to false, the css is not embedded in each page but instead includes an external call to <link rel="stylesheet" href="{{.Site.BaseURL}}/css/style.min.css">
  UseCRP = false
  # Include the jQuery CDN in the <head> of your site?
  IncludeJQ = false
  UseDisqus = true
  disqusShortname = ""
  SitePublishDate = "2016-01-01"

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[taxonomies]
  tag = "tags"
  categories = "categories"





